-- Create Core Banking Schema
CREATE SCHEMA IF NOT EXISTS banking_core;

-- 1. Applications Table (بيانات العملاء وقت الطلب)
CREATE TABLE IF NOT EXISTS banking_core.applications (
    SK_ID_CURR INT PRIMARY KEY,
    TARGET INT,
    NAME_CONTRACT_TYPE VARCHAR(50),
    CODE_GENDER VARCHAR(5),
    FLAG_OWN_CAR VARCHAR(5),
    FLAG_OWN_REALTY VARCHAR(5),
    CNT_CHILDREN INT,
    AMT_INCOME_TOTAL NUMERIC(15, 2),
    AMT_CREDIT NUMERIC(15, 2),
    AMT_ANNUITY NUMERIC(15, 2),
    AMT_GOODS_PRICE NUMERIC(15, 2),
    NAME_INCOME_TYPE VARCHAR(100),
    NAME_EDUCATION_TYPE VARCHAR(100),
    NAME_FAMILY_STATUS VARCHAR(50),
    NAME_HOUSING_TYPE VARCHAR(100),
    DAYS_BIRTH INT,
    DAYS_EMPLOYED INT,
    OCCUPATION_TYPE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Bureau Table (سجل الاستعلام الائتماني الخارجي - iScore)
CREATE TABLE IF NOT EXISTS banking_core.bureau (
    SK_BUREAU_ID INT PRIMARY KEY,  
    SK_ID_CURR INT REFERENCES banking_core.applications(SK_ID_CURR),
    CREDIT_ACTIVE VARCHAR(20),
    CREDIT_CURRENCY VARCHAR(10),
    DAYS_CREDIT INT,
    CREDIT_DAY_OVERDUE INT,
    DAYS_CREDIT_ENDDATE INT,
    AMT_CREDIT_MAX_OVERDUE NUMERIC(15, 2),
    CNT_CREDIT_PROLONG INT,
    AMT_CREDIT_SUM NUMERIC(15, 2),
    AMT_CREDIT_SUM_DEBT NUMERIC(15, 2),
    AMT_CREDIT_SUM_LIMIT NUMERIC(15, 2),
    AMT_CREDIT_SUM_OVERDUE NUMERIC(15, 2),
    CREDIT_TYPE VARCHAR(100),
    DAYS_CREDIT_UPDATE INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Enable Logical Replication for Debezium CDC
ALTER TABLE banking_core.applications REPLICA IDENTITY FULL;
ALTER TABLE banking_core.bureau REPLICA IDENTITY FULL;